### ISSUE TITLE
Assess and Fix API Slowness

### ISSUE THREAD

**Issue by tobru** [projectsyn/lieutenant-api#115]
The API feels very slow when working with many objects (see integration in VSHN Portal). While this is at first sight a cosmetic issue, it hinders to have a good user feeling.

## Steps to Reproduce the Problem

1. Login to control.vshn.net
1. Browse around in Lieutenant section
1. Feel the slowness

## Actual Behavior

It's very slow, also reported by the Portal itself.

## Expected Behavior

It's fast.

**Comment by ccremer** [comment]
I've done some investigation.

Requests usually take 1.8s or more via curl on all environments (repeated a few times, but not really benchmarked):
```
time curl -H "${LIEUTENANT_AUTH}" https://api-dev.syn.vshn.net/tenants
0.02s user 0.01s system 2% cpu 1.935 total

time curl -H "${LIEUTENANT_AUTH}" https://api-int.syn.vshn.net/tenants      
0.03s user 0.01s system 1% cpu 2.019 total

time curl -H "${LIEUTENANT_AUTH}" https://api.syn.vshn.net/tenants 
0.03s user 0.01s system 1% cpu 2.065 total
```
Conclusion 1) The amount of tenants doesn't really have a noticable impact.

Trying out setting an empty dir for a cache:

1. disable ArgoCD sync
2. added `HOME=/home/cache` env var to deployment, as well as an `emptyDir` to `/home/cache`

Conclusion 2) The empty Dir with setting HOME doesn't have an effect.

I noticed though, after rolling out the change with the home dir, the first request took longer:
```
{..."host":"api-dev.syn.vshn.net","uri":"/tenants","user_agent":"curl/7.68.0","status":200,"latency_human":"4.167003658s"}
{..."host":"api-dev.syn.vshn.net","uri":"/tenants","user_agent":"curl/7.68.0","status":200,"latency_human":"1.72190163s"}
{..."host":"api-dev.syn.vshn.net","uri":"/tenants","user_agent":"curl/7.68.0","status":200,"latency_human":"1.712845063s"}
```

Suspicion: The cache may already work, there is something other than the cache slowing things down.
Conclusion 3) Need to further isolate the parts of the latency.

**Comment by ccremer** [comment]
Conclusion 4) It seems to be pretty consistent. The /clusters endpoint also takes at least 1.8 seconds with repeated calls.

**Comment by ccremer** [comment]
Conclusion 5) The Kubernetes API is not the part slowing requests down. Even with local `make run`, the listing of clusters takes about 5% of the request:
```go
...
	start := time.Now()

	clusterList := &synv1alpha1.ClusterList{}
	if err := ctx.client.List(ctx.context, clusterList, client.InNamespace(s.namespace)); err != nil {
		return err
	}
	clusters := []api.Cluster{}
	for _, cluster := range clusterList.Items {
		apiCluster := api.NewAPIClusterFromCRD(cluster)
		clusters = append(clusters, *apiCluster)
	}
	elapsed := time.Since(start)
	fmt.Printf("listing clusters took %s", elapsed)
...
```
```console
listing clusters took 106.407645ms
listing clusters took 81.840722ms
listing clusters took 91.585919ms
```

**Comment by ccremer** [comment]
Conclusion 6) The bulk of the request time goes into the authentication stack. Particularly https://github.com/projectsyn/lieutenant-api/blob/55ba6f638ad1767ba70720ee612595833e7be589/pkg/service/kubernetes_auth.go#L76-L94

Patching it:
```go
func getClientFromToken(token string) (client.Client, error) {
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		fmt.Printf("getClientFromToken took %s\n", elapsed)
	}()
	cfg, err := config.GetConfig()
	...
}
```
Results:
```
extracting token took 1.104µs
getClientFromToken took 2.035907757s
listing clusters took 147.095343ms
```

**Comment by ccremer** [comment]
Found it:
It's really `return client.New()` that takes 2s to run.
This client is coming from `controller-runtime`. Looking into `client.New()` itself, I can see that it **builds a new cache** for all cachable resource types, including CRDs **for every single request**.

The client from `controller-runtime` is meant for operators, where it's only one global client instance. It's unsuited for querying resources with different token every time.

Next course of actions that I see:
* Update controller-runtime to v0.8.x (we are on v0.5.2). This is a major API breaking change, and our target Kubernetes API would likely be bumped to v1.20 (currently: pinned to 1.16.2). However there's no guarantee that it'll work faster.
* Somehow try to reuse the same client. The `RestConfig` is passed via reference. It could be that we can update the token from the config without rebuilding the client instance. But we might need to use mutexes in order to not have race conditions or privilege escape in the middle of replacing tokens in the "global" instance. Again, no guarantee that it'll even works or solves the problem.
* We use the native client from kubernetes instead of the `controller-runtime`. We'll lose the integrated read cache (except we write our own cache) but I assume instantiating the plain client is fast enough. Requires significant re-engineering of the API endpoints, since the plain client is somewhat harder to use from a programmer's perspective.
* We're accessing the resources with the auth token from the API pod itself, not the passed-through token. We could keep the `controller-runtime` client, but would loose granular RBAC authorization of the user's token. If RBAC is still needed, we would need to implement our own authorization middleware, like our own version of `kubectl auth can-i list cluster`.
* We write our own client layer that directly talks to the Kubernetes API (it's JSON after all) but with easy support to supply a new authentication token for each request.

**Comment by tobru** [comment]
A few thoughts:

* Can we disable caching in `client.New()`? When looking at the [code](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client.go#L74) I'm not sure if that's possible. What puzzles me is the comment in the code: `The returned client reads *and* writes directly from the server (it doesn't use object caches)`. But I don't exactly understand what that means.
* Updating the `controller-runtime` might be worth a try. There are some things done regarding caching, e.g. https://github.com/kubernetes-sigs/controller-runtime/pull/1249.
* We could create a client per token and keep it around for a while and then trash it again to not use resources when not needed.

As I can see from the suggestions most (if not all) of the solutions would be a significant amount of work. Depending on that it might be worth to focus on #94 rather than fixing it.

**Comment by srueg** [comment]
Nice find!

I'd suggest to use an LRU cache to store the created clients and reuse them if the same token connects again.
E.g. https://github.com/hashicorp/golang-lru could work with the tokens (or a has of it) as key.

**Comment by ccremer** [comment]
>     * Can we disable caching in `client.New()`?

It's possible but you were looking in the master branch. With our version it's not possible AFAIK. Disabling cache resp. using client delegation is a thing in v0.8.x.

I think bumping the dependencies might be the least amount of work, even if it's not an 5-min task either.

Based on the discussion I suggest the following:
1. Update controller-runtime and try to disable cache or anything else that would reduce instantiation time. Bumping the dependencies is generally a good idea anyway?
2. Implement the LRU cache as Simon suggests. It doesn't look particularly hard to integrate the mentioned library.

**Comment by ccremer** [comment]
I tried to update the dependencies in #49 . I'm getting a panic at some point but can already confirm bumping to controller-runtime v0.8.3 without other changes, it still requires 2seconds:
```
⇨ http server started on [::]:8080
extracting token took 1.107µs
I0416 15:14:29.746815  665569 request.go:655] Throttling request took 1.04875608s, request: GET:https://rancher.vshn.net/k8s/clusters/c-c6j2w/apis/authentication.k8s.io/v1?timeout=32s
getClientFromToken took 2.262211336s
{"time":"2021-04-16T15:14:30.547527028+02:00","level":"-","prefix":"echo","file":"recover.go","line":"92","message":"[PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference goroutine 9 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1(0x1700470, 0x1000, 0x0, 0x185ad88, 0xc000539900)\n\t/home/chris/go/pkg/mod/github.com/labstack/echo/v4@v4.2.2/middleware/recover.go:77 +0x105\npanic(0x14cd7c0, 0x2106a00)\n\t/snap/go/7172/src/runtime/panic.go:965 +0x1b9\ngolang.org/x/time/rate.(*Limiter).WaitN(0xc000416f00, 0x0, 0x0, 0x1, 0x0, 0x0)\n\t/home/chris/go/pkg/mod/golang.org/x/time@v0.0.0-20201208040808-7e3f01d25324/rate/rate.go:237 +0xba\ngolang.org/x/time/rate.(*Limiter).Wait(...)\n\t/home/chris/go/pkg/mod/golang.org/x/time@v0.0.0-20201208040808-7e3f01d25324/rate/rate.go:219\nk8s.io/client-go/util/flowcontrol.(*tokenBucketRateLimiter).Wait(0xc00015b920, 0x0, 0x0, 0x215b380, 0x1480600)\n\t/home/chris/go/pkg/mod/k8s.io/client-go@v0.20.4/util/flowcontrol/throttle.go:106 +0x4b\nk8s.io/client-go/rest.(*Request).tryThrottle(0xc0004fc000, 0x0, 0x0, 0x1, 0x0)\n\t/home/chris/go/pkg/mod/k8s.io/client-go@v0.20.4/rest/request.go:587 +0xa5\nk8s.io/client-go/rest.(*Request).request(0xc0004fc000, 0x0, 0x0, 0xc0000df0c8, 0x0, 0x0)\n\t/home/chris/go/pkg/mod/k8s.io/client-go@v0.20.4/rest/request.go:860 +0x2d4\nk8s.io/client-go/rest.(*Request).Do(0xc0004fc000, 0x0, 0x0,
```
Next step: try to play around with cache settings

**Comment by ccremer** [comment]
Unfortunately it's not easily possible to instantiate a client with cache disabled:
```go
	return client.NewDelegatingClient(client.NewDelegatingClientInput{
		Client: ???,
		UncachedObjects: []client.Object{
			&synv1alpha1.Cluster{},
			&synv1alpha1.Tenant{},
			&synv1alpha1.GitRepo{},
		},
	}))
```
`NewDelegatingClient` is the only method the controller exposes, and there it asks for an existing client. Which we would have to create before but still being able to use different auth tokens. And the creation of the delegated client takes 2s already...

So, let's try using Simons LRU cache.

**Comment by ccremer** [comment]
Using the LRU cache seems to be very promising:
```
extracting token took 1.576µs
getClientFromToken took 6.364µs
listing clusters took 131.299µs
```
