### ISSUE TITLE
Provide a simple way to start the Lieutenant API

### ISSUE THREAD

**Issue by Xcalizorz** [projectsyn/lieutenant-api#132]
## Context

As a user, I want to have the ability to easily start the lieutenant API without having to go through the hassle of installing all needed software like `go`, `make` or cloning this repository, etc. 

Preferentially, I would like to use docker to run an instance of the API, so I can work/try out on `Commodore` more easily.

Possible way of running:

```bash
    docker run --rm -v $HOME/.kube/myconfig:$HOME/.kube/myconfig -d -p 8080:8080 vshn/lieutenant-api
```

If you like this proposal, I can share a PR with the solution I'm currently using. The only problem I'm facing is that I don't know how to get the API Token in a local instance.

## Alternatives

Can not think of any.

**Comment by tobru** [comment]
Thanks for trying out Project Syn!

There already is a [Dockerfile](https://github.com/projectsyn/lieutenant-api/blob/master/Dockerfile) and an automated image build available. All the images are available on Docker Hub under the [Project Syn](https://hub.docker.com/u/projectsyn) org.

You might also want to have a look at the [Getting Started guide](https://syn.tools/syn/tutorials/getting-started.html), which could answer some questions you have.

**Comment by Xcalizorz** [comment]
Thanks for your quick feedback!
