### ISSUE TITLE
More memorable cluster and tenant names

### ISSUE THREAD

**Issue by corvus-ch** [projectsyn/lieutenant-api#30]
Today I have had the chance to work with the lieutenant API while synfecting several clusters. Even with smaller numbers of tenants and clusters, I got confused and had to concentrate really hard to not mix them up. I suggest to switch to a more memorable naming scheme.

Personally, I prefer something in the format `<adjective>-<noun>-<four digit number>` as it can be generated with https://github.com/taion809/haikunator.

**Comment by srueg** [comment]
Current implementation: https://github.com/projectsyn/lieutenant-api/blob/dedbbc61cceb195a66175f18cb746f0738f48292/pkg/api/utils.go#L49
