### ISSUE TITLE
Introduce Goreleaser to pipeline

### ISSUE THREAD

**Issue by ccremer** [projectsyn/lieutenant-api#33]
Use [Goreleaser](https://github.com/goreleaser/goreleaser) to build and release new releases to GitHub.

Goreleaser has several advanced packaging features:
* Docker build & push, including floating tag support
* Run `test` & `vet` before build, with Hooks
* Create checksum files, and sign with GPG
* Attach binary (or zip archive) to releases
* Create DEB and RPM packages

Example Implementation which implements all of the above (including pipeline)
* .goreleaser file: https://github.com/ccremer/znapzend-exporter/blob/master/.goreleaser.yml
* Example GitHub Action usage: https://github.com/ccremer/znapzend-exporter/blob/master/.github/workflows/build.yml

**Comment by srueg** [comment]
As discussed, I don't see the benefit goreleaser would bring to this project. We only need container images as artefacts and we already have a Makefile to run all the steps (vet, test, build, etc.). This also allows us to have the same setup for all projects and it's not golang specific.

Anyways, thanks for the input 👍
