### ISSUE TITLE
Cluster catalog Git repo default path via Tenant object

### ISSUE THREAD

**Issue by tobru** [projectsyn/lieutenant-api#41]
Leverage the new field in the `Tenant` object implemented in https://github.com/projectsyn/lieutenant-operator/issues/48 to figure out where to create the cluster catalog git repository when a cluster gets created with an empty `gitRepo` field.

This should make the two hardcoded value obsolete:
* https://github.com/projectsyn/lieutenant-api/blob/18961ed/pkg/api/utils.go#L190
* https://github.com/projectsyn/lieutenant-api/blob/18961ed/pkg/api/utils.go#L194

**Comment by srueg** [comment]
Closed in favor of https://github.com/projectsyn/lieutenant-operator/issues/109
