### ISSUE TITLE
Make `gitRepo` in Tenant object mandatory

### ISSUE THREAD

**Issue by tobru** [projectsyn/lieutenant-api#43]
Make the field `gitRepo.url` on the Tenant object mandatory.

While it is possible today to create a `Tenant` without specifying a `gitRepo.url`, it doesn't really make sense because in practice it's undefined where this git repo will be stored and it is most likely different per customer. With this change it shouldn't be possible anymore to create a Tenant without specifying where the tenant repo is stored.

**Comment by corvus-ch** [comment]
Similar to what I propose in https://github.com/projectsyn/lieutenant-operator/issues/48, I would also like to have some global default templating kicking in if `gitRepo.url` is undefined.

**Comment by srueg** [comment]
What would be such a default? I think we tried that and it didn't work. Especially if we require separate credentials for each tenant.

**Comment by corvus-ch** [comment]
You (@srueg) are probably referring to #42. And you got a point. Let us keep stuff simple for know. We can add that global default any time later if we really see the need for it.

**Comment by tobru** [comment]
Exactly, keep it simple for now. If we (or the community) ever has the need for a default in the future, we can change the behavior then.
