### ISSUE TITLE
Expose Object Annotations in API

### ISSUE THREAD

**Issue by tobru** [projectsyn/lieutenant-api#66]
For various use cases we need the annotations of the Tenant and Cluster object exposed via the API so that annotations are available in the respective objects and can be created, read, updated and deleted.

Expand the OpenAPI schema for annotations support and implement the needed functionality in the API.

**Comment by srueg** [comment]
PR to expose annotations via API: https://github.com/projectsyn/lieutenant-api/pull/84

Should the labels also be exposed?

**Comment by tobru** [comment]
I don't see any use case for labels right now, so I propose to not expose labels for the time being. When we would find a use case we'll do it in a separate issue.
