### ISSUE TITLE
Filtering clusters by tenant does not work

### ISSUE THREAD

**Issue by mhutter** [projectsyn/lieutenant-api#95]
According to the documentation, [clusters can be filtered by tenant ID](https://syn.tools/lieutenant-api/references/index.html#_listclusters). This does not work.

## Steps to Reproduce the Problem

    curl -sS -H "$LIEUTENANT_AUTH" "https://${LIEUTENANT_URL}/clusters?tenant=t-xxx" | jq '.[].displayName'

## Actual Behavior
* List of ALL clusters in the API

## Expected Behavior
* List of the specific tenant's clusters.

## Workaround

    curl -sS -H "$LIEUTENANT_AUTH" "https://${LIEUTENANT_URL}/clusters" | jq '.[] | select(.tenant == "t-xxx") | .displayName'

**Comment by srueg** [comment]
You're absolutely right, this has never been implemented. The full list of clusters is always returned: https://github.com/projectsyn/lieutenant-api/blob/master/pkg/service/cluster.go#L30

It should be easy enough to extend this call to use a label selector if for a certain tenant should be filtered:
`syn.tools/tenant=$TENANT_ID`
