### ISSUE TITLE
Allow Setting ID in API

### ISSUE THREAD

**Issue by tobru** [projectsyn/lieutenant-api#98]
## Context

Allow to set the ID of the object to be created (`Tenant` or `Cluster`) instead of auto-generating it. If the ID is not passed, the ID should still be auto-generated.

## Alternatives

The generated IDs are not always a good idea and has been brought up as a usability issue from time to time. So the only alternative is not doing it.

**Comment by tobru** [comment]
Should we keep the prefixes? Currently we generate the names by adding a prefix `c-` for clusters and `t-` for tenants. I would want to keep this prefix, so that the ID passed to the creation API endpoints adds the prefix. So if I want to create e.g. a Tenant with the ID `acmecorp` the real ID would then be `t-acmecorp`. WDYT?

**Comment by ccremer** [comment]
I think we should keep the prefixes. I think there will be a time where someone decides to name both the tenant and cluster id to the same name, with prefixes we can differentiate and be more explicit to reduce confusion

**Comment by srueg** [comment]
Yes, good point. Otherwise a tenant and cluster with the same name would collide because they would get the same secret/serviceaccount and GitRepo object.

**Comment by ccremer** [comment]
should we otherwise specify certain constraints?
e.g.
* max length so that DNS still works (is it like 63 chars?)
* lowercase a-z and 0-9 only, and just dashes
* other?

**Comment by srueg** [comment]
We implicitly require DNS Label Names: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names

Because the name will end up in labels on objects.

**Comment by ccremer** [comment]
Then we should make this more explicit. I would actually add some input validation in the API if nothing exists yet, to catch such user errors ASAP.

**Comment by tobru** [comment]
No input validation needed, that's done by the Kubernetes API.

**Comment by tobru** [comment]
I propose to not do the prefixing (`c-` and `t-`) in the API but in the frontend (in VSHNs case the Portal). As we are planning to move away from the API over time this would have to be implemented in the frontend anyways. And the less business logic we build in the API, the better.
